**Instituto de Informática - UFG**

Disciplina: Inteligência Computacional

Prof. Cedric Luiz de Carvalho

---

Aluna(o): Arthur Gomes de Siqueira

Aluna(o): Ricardo Ataide de Oliveira Junior

---

Grupo ( D )

---

Papel no grupo: 

---

#Especificação do problema : Algoritmos genéticos

Os anos de 2020 e 2021 estão sendo anos trágicos. Mais de 156 milhões de pessoas já foram infectadas e mais de 3,25 milhões de pessoas já morreram acometidas pela COVID-19 no mundo. Um grande número de cientistas está trabalhando com afinco para produzir medicamentos que possam minimizar os efeitos do vírus. Um dos fatores que pode influenciar a maior ou menor gravidade da manifestação doença nos pacientes infectados pelo vírus é a sua alimentação.

Utilizando as bases de [dados sobre a alimentação](https://www.kaggle.com/mariaren/covid19-healthy-diet-dataset), implemente uma ferramenta computacional, que aplique a técnica de algoritmos genéticos para identificar a melhor dieta alimentar que possa minimizar os efeitos da doença.

## O trabalho

O trabalho deve ser feito em grupos, conforme definido. Cada grupo deverá entregar apenas um produto final para ser avaliado pelo professor. Apesar do trabalho ser feito em grupos, a avaliação de cada aluno será feita individualmente.

**Recomendações:**

   O primeiro passo para resolver um problema é entendê-lo muito bem, considerar o contexto e fazer as abstrações necessárias. A seguir, para não "reinventar a roda" é preciso identificar como a comunidade resolveu o problema em questão, ou problemas parecidos, cuja solução possa ser mapeada para situação em análise. Desta forma, deve ser feito um estudo, o mais amplo possível sobre esse assunto. O próximo passo é o grupo se reunir e instanciar o modelo em estudo para o caso específico do problema a ser resolvido. Em paralelo, uma análise rigorosa deve ser feita na base de dados a fim de prepará-la para seu uso no modelo. Finalmente, com o modelo bem compreendido e instanciado e os dados devidamente preparados, a implementação do modelo pode ser feita.

## Divisão de papéis:

* **Analista de dados:** deverá ficar responsável por fazer uma "Análise Exploratória de Dados" (AED), analisando a base de dados fornecida e preparando-a para ser usada na solução do problema. Esta análise deve produzir diversos gráficos que pemitam uma visão geral do comportamento dos dados.

* **Engenheiro de conhecimento:** deverá produzir a solução para o problema, utilizando a técnica estudada, o modelo proposto pelo grupo e a base de dados preparada pelo analista de dados.

### Primeira etapa:

(1) **Notebook descrevendo detalhadamente o modelo:**
* Um modelo é uma representação abstrata do mundo. No nosso caso, o "mundo" é o contexto onde o problema se insere. Desta forma, deve ser analisado com cuidado o que deve e o que não deve ser considerado. Por exemplo, se a base de dados tem 30 colunas, todas elas deverão ser utilizadas na implementação? Algumas poderão ser desconsideradas? Por quê?
* Para utilizar a técnica em estudo, é preciso conhecê-la muito bem. Assim, nesta etapa, **deve ser feita uma descrição detalhada do problema e da técnica a ser utilizada.**
* Deve ser elaborado um modelo com base na técnica em estudo.
* O notebook, descrevendo o problema, a técnica em questão e o modelo elaborado deverá ser submetido na Plataforma Turing, até dia 03/11/2021. Os modelos serão discutidos com a turma no dia 04/11/2021.

### Segunda etapa:

(2) **Notebook contendo a Análise Exploratória dos Dados**

(3) **Notebook contendo a solução para o problema** 

(4) **Um vídeo explicando detalhadamente como a técnica estudada foi utilizada para resolver o problema proposto** . O vídeo NÃO deve ser uma apresentação do notebook nem deve apresentar detalhes de codificação. Deve trazer uma descrição do problema, do modelo utilizado e da solução desenvolvida, de preferência utilizando slides ou algo parecido. Preferencialmente, o grupo deve enviar um *link* para o local onde o vídeo está armazenado.


**Observação:** poderão ser utilizados códigos desenvolvidos pelo grupo e/ou códigos de terceiros. No caso de se usar códigos desenvolvidos por terceiros, o autor desses códigos deve ser devidamente referenciado e os códigos devem ser devidamente documentados (comentários no próprio código e fora dele).

Os produtos da segunda etapa deverão ser submetidos na Plataforma Turing até 09/11/2021.

# Analise Exploratoria dos dados

In [ ]:
#Fazendo upload dos arquivos
from google.colab import files
uploaded = files.upload()

Saving Fat_Supply_Quantity_Data.csv to Fat_Supply_Quantity_Data.csv
Saving Food_Supply_kcal_Data.csv to Food_Supply_kcal_Data.csv
Saving Food_Supply_Quantity_kg_Data.csv to Food_Supply_Quantity_kg_Data.csv
Saving Protein_Supply_Quantity_Data.csv to Protein_Supply_Quantity_Data.csv
Saving Supply_Food_Data_Descriptions.csv to Supply_Food_Data_Descriptions.csv

## Descrição dos dados

Temos cinco datasets com os nomes apresentados abaixo e com sua descrição:

- `Fat_Supply_Quantity_Data.csv`: Este conjunto de dados inclui a porcentagem de ingestão de gordura de diferentes tipos de alimentos em países ao redor do mundo. As últimas duas colunas também incluem contagens de casos de obesidade, desnutrição e COVID-19 como porcentagens da população total para fins de comparação.

- `Food_Supply_Quantity_kg_Data.csv`: Este conjunto de dados inclui a porcentagem de ingestão de alimentos (kg) em países ao redor do mundo. As últimas duas colunas também incluem contagens de casos de obesidade, desnutrição e COVID-19 como porcentagens da população total para fins de comparação.

- `Food_Supply_kcal_Data.csv`: Este conjunto de dados inclui a porcentagem de ingestão de energia (kcal) de diferentes tipos de alimentos em países ao redor do mundo. As últimas duas colunas também incluem contagens de casos de obesidade, desnutrição e COVID-19 como porcentagens da população total para fins de comparação.

- `Protein_Supply_Quantity_Data.csv`: Este conjunto de dados inclui a porcentagem de ingestão de proteínas de diferentes tipos de alimentos em países ao redor do mundo. As últimas duas colunas também incluem contagens de casos de obesidade, desnutrição e COVID-19 como porcentagens da população total para fins de comparação.

- `Supply_Food_Data_Descriptions.csv`: Este conjunto de dados é obtido da FAO.org e é usado para mostrar os tipos específicos de alimentos que pertencem a cada categoria para os conjuntos de dados acima.

## Analisando os campos(linhas e colunas)

**Linhas**:

Cada linha representa um **país**.

**Colunas**:
* Alcoholic Beverages:
Quantidade de bebida alcoolica

* Animal Products: 
Alimentos de origem natural

* Animal fats: Gordura Animal
* Aquatic Products, Other: Outros produtos aquáticos
* Cereals - Excluding Beer: Cereais 
* Eggs: Ovo
* Fish, Seafood: Peixe, Frutos do mar
* Fruits - Excluding Wine: frutos excluindo vinho
* Meat: carne
* Miscellaneous: variados
* Milk - Excluding Butter: Laticínios, excluindo manteiga
* Offals: - Miúdos comestíveis
* Oilcrops: - Oleaginosos
* Pulses: Leguminosa
* Spices: Pimenta
* Starchy Roots: - Raízes com amido
* Stimulants: - Estimulantes
* Sugar Crops: - Cana de açúcar/beterraba doce
* Sugar & Sweeteners: Açúcar e Adoçantes
* Treenuts: - Nozes
* Vegetal Products: - Produtos vegetais
* Vegetables: vegetais
* Obesity: taxa de obesidade
* Undernourished: taxa de desnutrição
* Confirmed: taxa de infectados com COVID-19
* Deaths: taxa de mortos com COVID-19
* Recouvered: taxa de recuperados de COVID-19
* Active: - Porcentagem de casos COVID-19 ativos
* Population: população total do país

* Unit (all except Population): indica a unidade usada em todas as colunas exceto population

## Arrumando os datasets

In [ ]:
import pandas as pd

#Descricao das comidas em categorias
pd.set_option("max_colwidth", 200)
pd.read_csv('Supply_Food_Data_Descriptions.csv')

                  Categories                                                                                                                                                                                                    Items
0        Alcoholic Beverages                                                                                                                                Alcohol, Non-Food; Beer; Beverages, Alcoholic; Beverages, Fermented; Wine
1                Animal fats                                                                                                                                 Butter, Ghee; Cream; Fats, Animals, Raw; Fish, Body Oil; Fish, Liver Oil
2            Animal Products  Aquatic Animals, Others; Aquatic Plants; Bovine Meat; Butter, Ghee; Cephalopods; Cream; Crustaceans; Demersal Fish; Eggs; Fats, Animals, Raw; Fish, Body Oil; Fish, Liver Oil; Freshwater Fish; Mari...
3    Aquatic Products, Other                                                                                                                                           Aquatic Animals, Others; Aquatic Plants; Meat, Aquatic Mammals
4   Cereals - Excluding Beer                                 Barley and products; Cereals, Other; Maize and products; Millet and products; Oats; Rice (Milled Equivalent); Rye and products; Sorghum and products; Wheat and products
5                       Eggs                                                                                                                                                                                                     Eggs
6              Fish, Seafood                                                                                              Cephalopods; Crustaceans; Demersal Fish; Freshwater Fish; Marine Fish, Other; Molluscs, Other; Pelagic Fish
7    Fruits - Excluding Wine  Apples and products; Bananas; Citrus, Other; Dates; Fruits, Other; Grapefruit and products; Grapes and products (excl wine); Lemons, Limes and products; Oranges, Mandarines; Pineapples and product...
8                       Meat                                                                                                                                      Bovine Meat; Meat, Other; Mutton & Goat Meat; Pigmeat; Poultry Meat
9    Milk - Excluding Butter                                                                                                                                                                                  Milk - Excluding Butter
10             Miscellaneous                                                                                                                                                                               Infant food; Miscellaneous
11                    Offals                                                                                                                                                                                           Offals, Edible
12                  Oilcrops                    Coconuts - Incl Copra; Cottonseed; Groundnuts (Shelled Eq); Oilcrops, Other; Olives (including preserved); Palm kernels; Rape and Mustardseed; Sesame seed; Soyabeans; Sunflower seed
13                    Pulses                                                                                                                                                                  Beans; Peas; Pulses, Other and products
14                    Spices                                                                                                                                                                   Cloves; Pepper; Pimento; Spices, Other
15             Starchy Roots                                                                                                                          Cassava and products; Potatoes and products; Roots, Other; Sweet potatoes; Yams
16                Stimulants                                                                                                                                      Cocoa Beans and products; Coffee and products; Tea (including mate)
17        Sugar & Sweeteners                                                                                                                                  Honey; Sugar (Raw Equivalent); Sugar non-centrifugal; Sweeteners, Other
18               Sugar Crops                                                                                                                                                                                   Sugar beet; Sugar cane
19                  Treenuts                                                                                                                                                                                        Nuts and products
20            Vegetable Oils  Coconut Oil; Cottonseed Oil; Groundnut Oil; Maize Germ Oil; Oilcrops Oil, Other; Olive Oil; Palm Oil; Palmkernel Oil; Rape and Mustard Oil; Ricebran Oil; Sesameseed Oil; Soyabean Oil; Sunflowersee...
21                Vegetables                                                                                                                                                         Onions; Tomatoes and products; Vegetables, Other
22          Vegetal Products  Alcohol, Non-Food; Apples and products; Bananas; Barley and products; Beans; Beer; Beverages, Alcoholic; Beverages, Fermented; Cassava and products; Cereals, Other; Citrus, Other; Cloves; Cocoa Be...

## Analisando os datasets com os dados

In [ ]:
data_fat = pd.read_csv('Fat_Supply_Quantity_Data.csv')
data_fat

                                Country  ...  Unit (all except Population)
0                           Afghanistan  ...                             %
1                               Albania  ...                             %
2                               Algeria  ...                             %
3                                Angola  ...                             %
4                   Antigua and Barbuda  ...                             %
..                                  ...  ...                           ...
165  Venezuela (Bolivarian Republic of)  ...                             %
166                             Vietnam  ...                             %
167                               Yemen  ...                             %
168                              Zambia  ...                             %
169                            Zimbabwe  ...                             %

[170 rows x 32 columns]

In [ ]:
data_comida_kg = pd.read_csv('Food_Supply_Quantity_kg_Data.csv')
data_comida_kg

                                Country  ...  Unit (all except Population)
0                           Afghanistan  ...                             %
1                               Albania  ...                             %
2                               Algeria  ...                             %
3                                Angola  ...                             %
4                   Antigua and Barbuda  ...                             %
..                                  ...  ...                           ...
165  Venezuela (Bolivarian Republic of)  ...                             %
166                             Vietnam  ...                             %
167                               Yemen  ...                             %
168                              Zambia  ...                             %
169                            Zimbabwe  ...                             %

[170 rows x 32 columns]

In [ ]:
data_comida_kcal = pd.read_csv('Food_Supply_kcal_Data.csv')
data_comida_kcal

                                Country  ...  Unit (all except Population)
0                           Afghanistan  ...                             %
1                               Albania  ...                             %
2                               Algeria  ...                             %
3                                Angola  ...                             %
4                   Antigua and Barbuda  ...                             %
..                                  ...  ...                           ...
165  Venezuela (Bolivarian Republic of)  ...                             %
166                             Vietnam  ...                             %
167                               Yemen  ...                             %
168                              Zambia  ...                             %
169                            Zimbabwe  ...                             %

[170 rows x 32 columns]

In [ ]:
data_protein = pd.read_csv('Protein_Supply_Quantity_Data.csv')
data_protein

                                Country  ...  Unit (all except Population)
0                           Afghanistan  ...                             %
1                               Albania  ...                             %
2                               Algeria  ...                             %
3                                Angola  ...                             %
4                   Antigua and Barbuda  ...                             %
..                                  ...  ...                           ...
165  Venezuela (Bolivarian Republic of)  ...                             %
166                             Vietnam  ...                             %
167                               Yemen  ...                             %
168                              Zambia  ...                             %
169                            Zimbabwe  ...                             %

[170 rows x 32 columns]

## Verificando se temos varias NaNs no banco de dados

In [ ]:
data_fat.isna().any()

Country                         False
Alcoholic Beverages             False
Animal Products                 False
Animal fats                     False
Aquatic Products, Other         False
Cereals - Excluding Beer        False
Eggs                            False
Fish, Seafood                   False
Fruits - Excluding Wine         False
Meat                            False
Miscellaneous                   False
Milk - Excluding Butter         False
Offals                          False
Oilcrops                        False
Pulses                          False
Spices                          False
Starchy Roots                   False
Stimulants                      False
Sugar Crops                     False
Sugar & Sweeteners              False
Treenuts                        False
Vegetal Products                False
Vegetable Oils                  False
Vegetables                      False
Obesity                          True
Undernourished                   True
Confirmed                        True
Deaths                           True
Recovered                        True
Active                           True
Population                      False
Unit (all except Population)    False
dtype: bool

In [ ]:
data_comida_kg.isna().any()

Country                         False
Alcoholic Beverages             False
Animal fats                     False
Animal Products                 False
Aquatic Products, Other         False
Cereals - Excluding Beer        False
Eggs                            False
Fish, Seafood                   False
Fruits - Excluding Wine         False
Meat                            False
Milk - Excluding Butter         False
Miscellaneous                   False
Offals                          False
Oilcrops                        False
Pulses                          False
Spices                          False
Starchy Roots                   False
Stimulants                      False
Sugar & Sweeteners              False
Sugar Crops                     False
Treenuts                        False
Vegetable Oils                  False
Vegetables                      False
Vegetal Products                False
Obesity                          True
Undernourished                   True
Confirmed                        True
Deaths                           True
Recovered                        True
Active                           True
Population                      False
Unit (all except Population)    False
dtype: bool

In [ ]:
data_comida_kcal.isna().any()

Country                         False
Alcoholic Beverages             False
Animal Products                 False
Animal fats                     False
Aquatic Products, Other         False
Cereals - Excluding Beer        False
Eggs                            False
Fish, Seafood                   False
Fruits - Excluding Wine         False
Meat                            False
Milk - Excluding Butter         False
Miscellaneous                   False
Offals                          False
Oilcrops                        False
Pulses                          False
Spices                          False
Starchy Roots                   False
Stimulants                      False
Sugar Crops                     False
Sugar & Sweeteners              False
Treenuts                        False
Vegetal Products                False
Vegetable Oils                  False
Vegetables                      False
Obesity                          True
Undernourished                   True
Confirmed                        True
Deaths                           True
Recovered                        True
Active                           True
Population                      False
Unit (all except Population)    False
dtype: bool

In [ ]:
data_protein.isna().any()

Country                         False
Alcoholic Beverages             False
Animal Products                 False
Animal fats                     False
Aquatic Products, Other         False
Cereals - Excluding Beer        False
Eggs                            False
Fish, Seafood                   False
Fruits - Excluding Wine         False
Meat                            False
Milk - Excluding Butter         False
Offals                          False
Oilcrops                        False
Pulses                          False
Spices                          False
Starchy Roots                   False
Stimulants                      False
Sugar Crops                     False
Sugar & Sweeteners              False
Treenuts                        False
Vegetal Products                False
Vegetable Oils                  False
Vegetables                      False
Miscellaneous                   False
Obesity                          True
Undernourished                   True
Confirmed                        True
Deaths                           True
Recovered                        True
Active                           True
Population                      False
Unit (all except Population)    False
dtype: bool

### Resultado 

As colunas Obesity, Undernourished, Confirmed, Deaths, Recovered e Active possuem NaNs.

### Quantidade de paises que tem valores com NaNs

In [ ]:
#Quantidade de paises que tem valores com NaNs
linhas_com_NaNs_valores = data_fat[data_fat.isna().any(axis=1)].shape[0]
qtd_de_linhas_com_NaN = data_fat.shape[0]

texto = "São " + str(linhas_com_NaNs_valores) + ' linhas (países) com pelo menos um NaN de ' + str(qtd_de_linhas_com_NaN) + ' países ' + str(linhas_com_NaNs_valores/qtd_de_linhas_com_NaN*100) + '%'
print(texto)

São 16 linhas (países) com pelo menos um NaN de 170 países 9.411764705882353%

### Análise de Tipos

Todos os tipos são float(real) tirando Country, Undernourished e Unit (all except Population).

In [ ]:
data_fat.dtypes

Country                          object
Alcoholic Beverages             float64
Animal Products                 float64
Animal fats                     float64
Aquatic Products, Other         float64
Cereals - Excluding Beer        float64
Eggs                            float64
Fish, Seafood                   float64
Fruits - Excluding Wine         float64
Meat                            float64
Miscellaneous                   float64
Milk - Excluding Butter         float64
Offals                          float64
Oilcrops                        float64
Pulses                          float64
Spices                          float64
Starchy Roots                   float64
Stimulants                      float64
Sugar Crops                     float64
Sugar & Sweeteners              float64
Treenuts                        float64
Vegetal Products                float64
Vegetable Oils                  float64
Vegetables                      float64
Obesity                         float64
Undernourished                   object
Confirmed                       float64
Deaths                          float64
Recovered                       float64
Active                          float64
Population                      float64
Unit (all except Population)     object
dtype: object

In [ ]:
data_comida_kg.dtypes

Country                          object
Alcoholic Beverages             float64
Animal fats                     float64
Animal Products                 float64
Aquatic Products, Other         float64
Cereals - Excluding Beer        float64
Eggs                            float64
Fish, Seafood                   float64
Fruits - Excluding Wine         float64
Meat                            float64
Milk - Excluding Butter         float64
Miscellaneous                   float64
Offals                          float64
Oilcrops                        float64
Pulses                          float64
Spices                          float64
Starchy Roots                   float64
Stimulants                      float64
Sugar & Sweeteners              float64
Sugar Crops                     float64
Treenuts                        float64
Vegetable Oils                  float64
Vegetables                      float64
Vegetal Products                float64
Obesity                         float64
Undernourished                   object
Confirmed                       float64
Deaths                          float64
Recovered                       float64
Active                          float64
Population                      float64
Unit (all except Population)     object
dtype: object

In [ ]:
data_comida_kcal.dtypes

Country                          object
Alcoholic Beverages             float64
Animal Products                 float64
Animal fats                     float64
Aquatic Products, Other         float64
Cereals - Excluding Beer        float64
Eggs                            float64
Fish, Seafood                   float64
Fruits - Excluding Wine         float64
Meat                            float64
Milk - Excluding Butter         float64
Miscellaneous                   float64
Offals                          float64
Oilcrops                        float64
Pulses                          float64
Spices                          float64
Starchy Roots                   float64
Stimulants                      float64
Sugar Crops                     float64
Sugar & Sweeteners              float64
Treenuts                        float64
Vegetal Products                float64
Vegetable Oils                  float64
Vegetables                      float64
Obesity                         float64
Undernourished                   object
Confirmed                       float64
Deaths                          float64
Recovered                       float64
Active                          float64
Population                      float64
Unit (all except Population)     object
dtype: object

In [ ]:
#analisando o Undernourished

pd.set_option("max_rows", 100)
data_fat['Undernourished'].value_counts()

<2.5    44
2.7      3
6.2      3
7.1      3
16.5     3
4.3      2
3.6      2
8.5      2
9        2
4.8      2
6.3      2
20.6     2
3.9      2
3.5      2
5.5      2
13.4     2
3.4      2
7.9      2
5.7      2
27.9     1
17.1     1
4.6      1
38.9     1
4.5      1
14.5     1
27.3     1
19       1
9.5      1
9.3      1
9.9      1
3.2      1
16.1     1
13.3     1
49.3     1
13.1     1
37.5     1
29.4     1
46.7     1
4.2      1
20.1     1
12.9     1
6.5      1
7.8      1
8.3      1
37.2     1
24.9     1
2.8      1
17       1
10.4     1
5.6      1
8.9      1
10.6     1
10.1     1
12.2     1
36.8     1
8        1
10.7     1
2.5      1
21.2     1
7.2      1
20       1
15.2     1
25.6     1
30.7     1
7.5      1
44.4     1
16.4     1
26.4     1
11.3     1
59.6     1
10       1
40.3     1
6.8      1
20.3     1
10.2     1
10.3     1
10.5     1
14.7     1
3.7      1
7        1
51.3     1
18.9     1
2.9      1
4.9      1
17.5     1
11       1
8.1      1
5.4      1
41       1
9.7      1
47.8     1
29       1
29.8     1
2.6      1
28       1
25       1
8.7      1
12.6     1
Name: Undernourished, dtype: int64

### Coluna Undernourished

Temos valores do tipo `<2.5`, que significa que ele está no intervalo de 0 até 2.5, entao acaba que o pandas entende que é uma string e acaba declarando-o como object inves de float. So converter `<2.5` para o valor médio `1.25` e passar para float.*texto em itálico*

In [ ]:
#fazendo os reparos como mencionado anteriormente
data_fat['Undernourished'] = data_fat['Undernourished'].str.replace('<2.5', '1.25')
data_fat['Undernourished'] = data_fat['Undernourished'].astype(float)

data_comida_kg['Undernourished'] = data_comida_kg['Undernourished'].str.replace('<2.5', '1.25')
data_comida_kg['Undernourished'] = data_comida_kg['Undernourished'].astype(float)

data_comida_kcal['Undernourished'] = data_comida_kcal['Undernourished'].str.replace('<2.5', '1.25')
data_comida_kcal['Undernourished'] = data_comida_kcal['Undernourished'].astype(float)

data_protein['Undernourished'] = data_protein['Undernourished'].str.replace('<2.5', '1.25')
data_protein['Undernourished'] = data_protein['Undernourished'].astype(float)

In [ ]:
data_fat.dtypes

Country                          object
Alcoholic Beverages             float64
Animal Products                 float64
Animal fats                     float64
Aquatic Products, Other         float64
Cereals - Excluding Beer        float64
Eggs                            float64
Fish, Seafood                   float64
Fruits - Excluding Wine         float64
Meat                            float64
Miscellaneous                   float64
Milk - Excluding Butter         float64
Offals                          float64
Oilcrops                        float64
Pulses                          float64
Spices                          float64
Starchy Roots                   float64
Stimulants                      float64
Sugar Crops                     float64
Sugar & Sweeteners              float64
Treenuts                        float64
Vegetal Products                float64
Vegetable Oils                  float64
Vegetables                      float64
Obesity                         float64
Undernourished                  float64
Confirmed                       float64
Deaths                          float64
Recovered                       float64
Active                          float64
Population                      float64
Unit (all except Population)     object
dtype: object

In [ ]:
data_comida_kg.dtypes

Country                          object
Alcoholic Beverages             float64
Animal fats                     float64
Animal Products                 float64
Aquatic Products, Other         float64
Cereals - Excluding Beer        float64
Eggs                            float64
Fish, Seafood                   float64
Fruits - Excluding Wine         float64
Meat                            float64
Milk - Excluding Butter         float64
Miscellaneous                   float64
Offals                          float64
Oilcrops                        float64
Pulses                          float64
Spices                          float64
Starchy Roots                   float64
Stimulants                      float64
Sugar & Sweeteners              float64
Sugar Crops                     float64
Treenuts                        float64
Vegetable Oils                  float64
Vegetables                      float64
Vegetal Products                float64
Obesity                         float64
Undernourished                  float64
Confirmed                       float64
Deaths                          float64
Recovered                       float64
Active                          float64
Population                      float64
Unit (all except Population)     object
dtype: object

In [ ]:
data_comida_kcal.dtypes

Country                          object
Alcoholic Beverages             float64
Animal Products                 float64
Animal fats                     float64
Aquatic Products, Other         float64
Cereals - Excluding Beer        float64
Eggs                            float64
Fish, Seafood                   float64
Fruits - Excluding Wine         float64
Meat                            float64
Milk - Excluding Butter         float64
Miscellaneous                   float64
Offals                          float64
Oilcrops                        float64
Pulses                          float64
Spices                          float64
Starchy Roots                   float64
Stimulants                      float64
Sugar Crops                     float64
Sugar & Sweeteners              float64
Treenuts                        float64
Vegetal Products                float64
Vegetable Oils                  float64
Vegetables                      float64
Obesity                         float64
Undernourished                  float64
Confirmed                       float64
Deaths                          float64
Recovered                       float64
Active                          float64
Population                      float64
Unit (all except Population)     object
dtype: object

In [ ]:
data_protein.dtypes

Country                          object
Alcoholic Beverages             float64
Animal Products                 float64
Animal fats                     float64
Aquatic Products, Other         float64
Cereals - Excluding Beer        float64
Eggs                            float64
Fish, Seafood                   float64
Fruits - Excluding Wine         float64
Meat                            float64
Milk - Excluding Butter         float64
Offals                          float64
Oilcrops                        float64
Pulses                          float64
Spices                          float64
Starchy Roots                   float64
Stimulants                      float64
Sugar Crops                     float64
Sugar & Sweeteners              float64
Treenuts                        float64
Vegetal Products                float64
Vegetable Oils                  float64
Vegetables                      float64
Miscellaneous                   float64
Obesity                         float64
Undernourished                  float64
Confirmed                       float64
Deaths                          float64
Recovered                       float64
Active                          float64
Population                      float64
Unit (all except Population)     object
dtype: object

## Resultado final dos datasets atualizados

In [ ]:
data_fat

                                Country  ...  Unit (all except Population)
0                           Afghanistan  ...                             %
1                               Albania  ...                             %
2                               Algeria  ...                             %
3                                Angola  ...                             %
4                   Antigua and Barbuda  ...                             %
..                                  ...  ...                           ...
165  Venezuela (Bolivarian Republic of)  ...                             %
166                             Vietnam  ...                             %
167                               Yemen  ...                             %
168                              Zambia  ...                             %
169                            Zimbabwe  ...                             %

[170 rows x 32 columns]

In [ ]:
data_comida_kg

                                Country  ...  Unit (all except Population)
0                           Afghanistan  ...                             %
1                               Albania  ...                             %
2                               Algeria  ...                             %
3                                Angola  ...                             %
4                   Antigua and Barbuda  ...                             %
..                                  ...  ...                           ...
165  Venezuela (Bolivarian Republic of)  ...                             %
166                             Vietnam  ...                             %
167                               Yemen  ...                             %
168                              Zambia  ...                             %
169                            Zimbabwe  ...                             %

[170 rows x 32 columns]

In [ ]:
data_comida_kcal

                                Country  ...  Unit (all except Population)
0                           Afghanistan  ...                             %
1                               Albania  ...                             %
2                               Algeria  ...                             %
3                                Angola  ...                             %
4                   Antigua and Barbuda  ...                             %
..                                  ...  ...                           ...
165  Venezuela (Bolivarian Republic of)  ...                             %
166                             Vietnam  ...                             %
167                               Yemen  ...                             %
168                              Zambia  ...                             %
169                            Zimbabwe  ...                             %

[170 rows x 32 columns]

In [ ]:
data_protein

                                Country  ...  Unit (all except Population)
0                           Afghanistan  ...                             %
1                               Albania  ...                             %
2                               Algeria  ...                             %
3                                Angola  ...                             %
4                   Antigua and Barbuda  ...                             %
..                                  ...  ...                           ...
165  Venezuela (Bolivarian Republic of)  ...                             %
166                             Vietnam  ...                             %
167                               Yemen  ...                             %
168                              Zambia  ...                             %
169                            Zimbabwe  ...                             %

[170 rows x 32 columns]

## 3. Fazendo fusão das tabelas

In [ ]:
colunas_em_comum = [
    'Country',
    'Obesity',
    'Confirmed',
    'Deaths',
    'Recovered',
    'Active',
    'Population',
    'Undernourished',
    'Unit (all except Population)',
]

common = data_fat[colunas_em_comum[:-1]]

# remove as colunas em comuns e adiciona (label) ao final do nome de cada coluna
data_fat = data_fat.drop(columns=colunas_em_comum)
data_comida_kg = data_comida_kg.drop(columns=colunas_em_comum)
data_comida_kcal = data_comida_kcal.drop(columns=colunas_em_comum)
data_protein = data_protein.drop(columns=colunas_em_comum)

dfs = [common, data_fat, data_comida_kcal, data_comida_kg, data_protein]
dataset = pd.concat(dfs, axis=1) # concatena as colunas
dataset

                                Country  Obesity  ...  Vegetables  Miscellaneous
0                           Afghanistan      4.5  ...      1.1370         0.0462
1                               Albania     22.3  ...      3.2456         0.0544
2                               Algeria     26.6  ...      3.1267         0.1399
3                                Angola      6.8  ...      0.8133         0.0924
4                   Antigua and Barbuda     19.1  ...      1.6024         0.2947
..                                  ...      ...  ...         ...            ...
165  Venezuela (Bolivarian Republic of)     25.2  ...      1.0129         0.0267
166                             Vietnam      2.1  ...      3.7216         0.0389
167                               Yemen     14.1  ...      0.5448         0.0564
168                              Zambia      6.5  ...      0.8039         0.0592
169                            Zimbabwe     12.3  ...      0.5955         0.0586

[170 rows x 100 columns]

### Removendo NaNs

Como somente alguns paises possuem valores com NaNs que corresponde a 9% das linhas e são as mesmas dentre todos os datasets, o dataset final não terá essas linhas de NaNs, ou seja, iremos remover do dataset.

In [ ]:
dataset.dropna(inplace=True)

In [ ]:
dataset

                                Country  Obesity  ...  Vegetables  Miscellaneous
0                           Afghanistan      4.5  ...      1.1370         0.0462
1                               Albania     22.3  ...      3.2456         0.0544
2                               Algeria     26.6  ...      3.1267         0.1399
3                                Angola      6.8  ...      0.8133         0.0924
5                             Argentina     28.5  ...      1.0516         0.0000
..                                  ...      ...  ...         ...            ...
165  Venezuela (Bolivarian Republic of)     25.2  ...      1.0129         0.0267
166                             Vietnam      2.1  ...      3.7216         0.0389
167                               Yemen     14.1  ...      0.5448         0.0564
168                              Zambia      6.5  ...      0.8039         0.0592
169                            Zimbabwe     12.3  ...      0.5955         0.0586

[154 rows x 100 columns]

In [ ]:
#gerando um novo dataset com os dados atualizados e arrumados
dataset.to_csv('novo_dataset.csv')

In [ ]:
data_comida_kg.to_csv('data_kg.csv')
data_comida_kcal.to_csv('data_kcal.csv')
data_fat.to_csv('data_fat.csv')
data_protein.to_csv('data_proteina.csv')